name: flutter_auth0
description: A Flutter plugin to use Auth0 authentication
author: dev.dennysegura@gmail.com
homepage: https://gitlab.com/tangerine_mobile/flutter_auth0.git
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: